// svg2string.js
// get SVG generated by MorrisJS

function findSVG(node, arr) {
  console.log("findSVG('"+node.nodeName+"') arr.length="+arr.length);
  if (node && (node.nodeName.toUpperCase() == "SVG")) {
    console.log("SVG found - findSVG('"+node.nodeName+"') arr.length="+arr.length);
    arr.push(node);
  } else {
    // recursive on child nodes
    var children = node.childNodes;
     for (var i = 0; i < children.length; i++) {
        // Children are siblings to each other
        findSVG(children[i], arr);
     };
  }
}

function getArray4SVG(pID) {
  var vNode = document.getElementById(pID);
  var vArray = [];
  if (vNode) {
    findSVG(vNode,vArray);
    if (vArray.length > 0) {
      console.log(vArray.length+" SVG Images found");
    }
  } else {
    console.error("CALL: getMorris2SVG('"+pID+"') - DOM node with ID '"+pID+"' not found");
  }
  return vArray;
}

function getMorris2SVG(pID) {
  console.log("getMorris2SVG('"+pID+"')");
  var vArray = getArray4SVG(pID);
  var vSVG = "undefined SVG image";
  if (vArray.length > 0) {
    vSVG = '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n';
    vSVG += "<!-- Created with CSV2WikiChart - URL: https://niebert.github.io/csv2wikichart_app -->\n"
    vSVG += vArray[0].outerHTML;
  };
  return vSVG;
}
